kind: ConfigMap
apiVersion: v1
metadata:
  name: custom-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFGTCCAwGgAwIBAgIUC3ZOmJRIqC90/f9HRzBkNKSGQFMwDQYJKoZIhvcNAQEN
    BQAwHDEaMBgGA1UEAwwRc3BlbnNjb3QuZGRucy5uZXQwHhcNMjUxMjExMDEyNTE5
    WhcNMzUxMjA5MDEyNTE5WjAcMRowGAYDVQQDDBFzcGVuc2NvdC5kZG5zLm5ldDCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPAQQPZ71kGoySOMFi1bRS0j
    T08TxI922xivB3Sf9BsIYYVGMO0dG52OZCpimi4jxMs6igYbwlx6/47dvRYLkV4d
    QAgW9noUjEGA55BgtEn8fBA1QXe5XjECsogXcxGoODhZlyYJ6SrIzeiyyayiV79T
    0vzea8RojM2rjHL5mXTnc4/VfIp63wGj6HYvMhhDbZMbZYam/jt68E7RX8vnXhTT
    N3M7ddWQLeAgMY7PMGtobVYq8iXy/4LKp38vOD7Hl+BcwChtUtA58EP6lAMTb0n/
    OKZD5h806eK/XOTZKQTzsl+kwA3r/btPp5gDMtTIr0/BSolt5k7FIqxcKYXPBRMH
    oEJsqdewVccq3IUDrhO6aKr/GB2iLwXjycglLe0NN7Gt3RjHVdL39tUv0BPHBP4U
    u3Bqye3f8xBZNg7adTAXN/W0Fs01mVoI1BuZp4scei/TFDBf8g3jWxGuIIFeGyCa
    ArJdR/P29OxeZ/5bK+sdBJwx+d9lDnxAE/UBWrm5Vr5lS/ROGauU7zI+TuyGNeZ1
    QAT3AWf58d88o0ZIndLaGIshFBMq+CfCEPfVLo24DZyPjdgr9rTB3LC6n72YgPnY
    fvJwWhffyx5pJhYVExmOmub0E2/7liVvPcnTv5vluSB21gUGSdtvlDFky6NlaEf3
    wAY+H5G50t+as/spo1hlAgMBAAGjUzBRMB0GA1UdDgQWBBTX9RErEhJe2ndHy3vU
    IcN26xxzlTAfBgNVHSMEGDAWgBTX9RErEhJe2ndHy3vUIcN26xxzlTAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBDQUAA4ICAQDDMNMO7/4Zx3P6ngEgosnPLAH3
    ni0w7Fy8/QsqD1o/VAjZEjop8cPCwmQwxKs3YPb8la23du5bRM0hoH4MPMjcl7LA
    2uGyD9ZDAS+yyeplcxXSbJVVcu5PKgHoyUqzS5q8pjPgQtFaFS9DsxJkDPva2Ads
    Mkplz3xbgyKWGLX/Me3LA2clOjO43pHv8iwC3JHPnXYE2ad+ucnZrfUlsaVfZamA
    ZfOHF4ARlKJkFM3cGDvqfn6r8gaiHz2weB1jAU9uzRwLHP5L4CH3dYo+H9MIkwwS
    UiNaqZb787RrOYj5jvt5RzGr5xmWAERpDiF/7xbSGCue2WOOtgDarNpsTFYcVoxZ
    VC3WGMkO65y7vuIeKt0Lt3DzrZt4t6VGjnnhBi/rHT8pwJy9gCjJ+1CHpsIkZTOG
    6ruK9XEVZ0RTKzAGrP1ckUkNkwH0uG1zoNSR6mcGcNyUac18aS8yWg8BPt1JIsol
    3G7o//iH1LvgAYLkJ2Kd2WsK02YWl9K3RbXpFrhcgYkN9lLV4ojjN3OH53RBL0rg
    ywQIgRqprp3Gk4+WgF5DiZpO5TvmZoEUzNSi5Irhdlh0iSt+NZI9tn8LjuhIdy2M
    eGDA/tbW3vZwAx5bK+N+qd4L1BhT98jjQUnux3YdLScS5xfYooT1yhp1ge5pNKIQ
    E4NPvVtMrYOuYgZW8w==
    -----END CERTIFICATE-----